### ISSUE TITLE
Summarize Iterative search

### ISSUE THREAD

**Issue by felixleopoldo** [felixleopoldo/benchpress#2]
Bug when summarising iterative search

`Error in dag2essgraph(g) : Invalid graph passed to replaceUnprotected().
Calls: <Anonymous> -> dag2essgraph
Execution halted
Full Traceback (most recent call last):
  File "/users/staff/dmi-dmi/rios0000/anaconda3/envs/benchmark/lib/python3.8/site-packages/snakemake/executors.py", line 2141, in run_wrapper
    run(
  File "/users/staff/dmi-dmi/rios0000/git/benchpress/workflow/rules/algorithm_rules.smk", line 588, in __rule_summarise_itsearch
  File "/users/staff/dmi-dmi/rios0000/anaconda3/envs/benchmark/lib/python3.8/site-packages/snakemake/shell.py", line 176, in __new__
    raise sp.CalledProcessError(retcode, cmd)
`

**Comment by felixleopoldo** [comment]
The problem was that Iterative MCMC was estimating the dag by the endspace.
